openapi: 3.0.4
info:
  title: Python Flask
  description: Proyecto base para aplicaciones Flask con ejemplos de configuración, testing y buenas prácticas.
  termsOfService: https://swagger.io/terms/
  contact:
    email: byronvillegasm@gmail.com
  license:
    name: MIT
    url: https://github.com/byron-villegas/python-flask/blob/main/LICENSE
  version: 1.0.12
externalDocs:
  description: Repository
  url: https://github.com/byron-villegas/python-flask
servers:
  - url: http://localhost:5000
    description: Local Server
  - url : https://python-flask-sus3.onrender.com
    description: Production Server
tags:
  - name: Product
    description: Services related to products
paths:
  /products:
    get:
      tags:
        - Product
      summary: Find all products
      description: Find all products
      operationId: findAllProducts
      responses:
        '200':
          description: return all products successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{sku}:
    get:
      tags:
        - Product
      summary: Find product by sku
      description: Find product by sku
      operationId: findProductBySku
      parameters:
        - name: sku
          in: path
          required: true
          description: The sku of the product to retrieve
          schema:
            type: integer
            example: 123456
      responses:
        '200':
          description: return product successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 10
        sku:
          type: integer
          example: 123456
        imagen:
          type: string
          example: https://example.com/image.jpg
        nombre:
          type: string
          example: Nintendo Switch
        descripcion:
          type: string
          example: Consola de videojuegos Nintendo Switch
        caracteristicas:
          type: array
          items:
            type: Charasteristic
            example:
              titulo: Resolución
              valor: 1280x720
      Charasteristic:
        titulo:
          type: string
          example: Resolución
        valor:
          type: string
          example: 1280x720
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            "write:pets": modify pets in your account
            "read:pets": read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header